### ISSUE TITLE
Split jiraline into frontend and backend

### ISSUE THREAD

**Issue by marekjm** [posbit/jiraline#1]
I suggest splitting this project into two separate projects:
- `jiraline`: the library implementing JIRA API,
- `jiraline-front`: CLI frontend for `jiraline`,

This way I will be able to use the backend part to write a JIRA plugin for [issue](https://github.com/marekjm/issue).

**Comment by mserr** [comment]
I tried to use [jira-python](https://github.com/pycontribs/jira) as a backend for this project. Unfortunately it is very slow (two times) comparing to API calls which were made using requests library. So I decided not to use it. Nevertheless project looks interesting.
In your opinion what architecture such backend should has?
